### ISSUE TITLE
Fail to install in mac 10.10, python 2.7

### ISSUE THREAD

**Issue by rylanchiu** [tmiasko/pyjags#2]
Collecting pyjags
	  Downloading pyjags-1.0.0.tar.gz (62kB)
	    100% |################################| 65kB 4.2MB/s 
	[?25h    Complete output from command python setup.py egg_info:
	    Traceback (most recent call last):
	      File "<string>", line 1, in <module>
	      File "/private/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/pip-build-yuHm33/pyjags/setup.py", line 68, in <module>
	        add_jags(ext)
	      File "/private/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/pip-build-yuHm33/pyjags/setup.py", line 46, in add_jags
	        version = add_pkg_config(ext, 'jags')
	      File "/private/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/pip-build-yuHm33/pyjags/setup.py", line 34, in add_pkg_config
	        output = subprocess.check_output(args)
	      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
	        process = Popen(stdout=PIPE, *popenargs, **kwargs)
	      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
	        errread, errwrite)
	      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
	        raise child_exception
	    OSError: [Errno 2] No such file or directory

	    ----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/pip-build-yuHm33/pyjags

**Comment by tmiasko** [comment]
It looks like you don't have pkg-config installed. Let me know if installing it helps. 
This error message should be more informative in development version available from git.

**Comment by rylanchiu** [comment]
Yes it helps. Thanks a lot!
