### ISSUE TITLE
Unable to install on Mac OSX 10.10.5 with LLVM 6.1.0

### ISSUE THREAD

**Issue by noctknight** [tmiasko/pyjags#5]
System configuration:
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
clang: warning: argument unused during compilation: '-stdlib=libstdc++'

Installation throw an error saying:

pybind11/include/pybind11/common.h:71:10: fatal error: 'unordered_set' file not found
    #include <unordered_set>

**Comment by tmiasko** [comment]
The unordered_set header is part of standard since C++11. It looks like the
implementation of C++ standard library used by your clang does not provide it yet.

Upgrading it could help. Just make sure to compile JAGS and pyjags with the
same compiler flags, otherwise you might have to deal with all kinds of nasty
ABI compatibility problems.

**Comment by crsqq** [comment]
I can compile it if I change the compiler:

`CC=gcc-6 CXX=g++-6 pip3 install --no-cache pyjags`

But then I get another error when I try to import pyjags...

```
python3 -c 'import pyjags'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/*/anaconda/lib/python3.5/site-packages/pyjags/__init__.py", line 16, in <module>
    from .model import *
  File "/Users/*/anaconda/lib/python3.5/site-packages/pyjags/model.py", line 21, in <module>
    from .console import Console, DUMP_ALL, DUMP_DATA, DUMP_PARAMETERS
ImportError: dlopen(/Users/*/anaconda/lib/python3.5/site-packages/pyjags/console.cpython-35m-darwin.so, 2): Symbol not found: __ZN5Model12rngFactoriesB5cxx11Ev
  Referenced from: /Users/*/anaconda/lib/python3.5/site-packages/pyjags/console.cpython-35m-darwin.so
  Expected in: dynamic lookup
```

**Comment by martinfthomsen** [comment]
I have the same problem. By googling I found this post which might be relevant:
https://groups.google.com/forum/#!topic/google-ctemplate/aute0rbWKwg
> Trouble is the use of unordered_map and unordered_set. These are no longer in the tr1 namespace, but in std.

I hope you can make sense of this, and solve the problem?

**Comment by mshabram** [comment]
This solved the problem for me:

https://stackoverflow.com/questions/33738885/python-setuptools-not-including-c-standard-library-headers

```
export MACOSX_DEPLOYMENT_TARGET=10.9
pip3 install pyjags
```

**Comment by mshabram** [comment]
This post helped me solve this problem:

https://stackoverflow.com/questions/33738885/python-setuptools-not-including-c-standard-library-headers

`>>> export MACOSX_DEPLOYMENT_TARGET=10.9`
`>>> pip3 install pyjags`
